name: agro

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x] 

    steps:
      - name: Git clone my repo
        uses : actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Connect to server
        uses: appleboy/ssh-action@master
        with:
          host: '185.129.49.235'
          username: 'root'
          password: ${{ secrets.SSH_PASSWORD }}
          port: "22"
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /var/www/agro-web
            git pull
            npm install
            pm2 delete all
            pm2 start "npm run dev" --name agro-web
